#服务器端口
server:
  port: 8080
spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: 5c5ac9f4-2119-4536-9b95-3e4266215774
        credential:
          client-id: c625532e-a36d-4789-85e3-52101552884f
          client-secret: 3Zj8Q~jmjh53h944DPs4lVKkCH_6k4QxEX~DxatW
  output:
    ansi:
      enabled: DETECT
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tr_chat
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#上传配置
upload:
  #物理路径
  path: E:/uploads/
#缓存配置
cache:
  open: true
  name: Redis
  clock:
    #使用cron表达式
    private: "*/10 * * * * ?"
    group: "*/5 * * * * ?"
